# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t-i6pzKSnH6tiGrY9s_6TWINfZ3xgBSL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_squared_error

data = pd.read_csv('/content/Nat_Gas.csv')  # Replace 'your_data.csv' with your actual file name
data['Dates'] = pd.to_datetime(data['Dates'], format='%m/%d/%y')
data.columns = ['Dates', 'Prices']  # Assuming the columns are named 'Dates' and 'Prices'
data['Dates'] = pd.to_datetime(data['Dates'])
data.set_index('Dates', inplace=True)

# Decompose the time series
decomposition = seasonal_decompose(data['Prices'], model='additive')

# Plot the decomposed components
plt.figure(figsize=(12, 8))
plt.subplot(411)
plt.plot(data['Prices'], label='Original')
plt.legend(loc='best')
# ... (rest of the plotting code)